version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: gamezone_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gamezone_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
